/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlithuvien;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author menbt
 */
public class thongKe extends javax.swing.JFrame {

    String sql1 = "select * from Bangsach group by ";
    String sql2 = "select * from Bangdocgia group by ";
    String sql3 = "select * from Bangnhanvien group by ";
    String sql4 = "select * from Bangmuontra group by ";
    String thongke = "";
    Vector row, rowtg;
    public thongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangThongKe = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        DG = new javax.swing.JMenu();
        DG_namsinh = new javax.swing.JMenuItem();
        DG_quequan = new javax.swing.JMenuItem();
        DG_gioitinh = new javax.swing.JMenuItem();
        NV = new javax.swing.JMenu();
        NV_namsinh = new javax.swing.JMenuItem();
        NV_quequan = new javax.swing.JMenuItem();
        NV_gioitinh = new javax.swing.JMenuItem();
        Sach = new javax.swing.JMenu();
        Sach_tacgia = new javax.swing.JMenuItem();
        Sach_theloai = new javax.swing.JMenuItem();
        Sach_NhaXB = new javax.swing.JMenuItem();
        Sach_namXB = new javax.swing.JMenuItem();
        MT = new javax.swing.JMenu();
        MT_ngay = new javax.swing.JMenuItem();
        MT_sachtheongay = new javax.swing.JMenuItem();
        MT_tiencoctheongay = new javax.swing.JMenuItem();
        MT_sodocgiatheongay = new javax.swing.JMenuItem();
        MT_tienphattheongay = new javax.swing.JMenuItem();
        MT_madocgia = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bùi Thị Mến");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Kết quả thống kê");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 350, 60));

        bangThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(bangThongKe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 610, 240));

        DG.setText("Độc giả");

        DG_namsinh.setText("Theo năm sinh");
        DG_namsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DG_namsinhActionPerformed(evt);
            }
        });
        DG.add(DG_namsinh);

        DG_quequan.setText("Theo quê quán");
        DG.add(DG_quequan);

        DG_gioitinh.setText("Theo giới tính");
        DG.add(DG_gioitinh);

        jMenuBar1.add(DG);

        NV.setText("Nhân viên");

        NV_namsinh.setText("Theo Năm sinh");
        NV.add(NV_namsinh);

        NV_quequan.setText("Quê quán");
        NV.add(NV_quequan);

        NV_gioitinh.setText("Theo giới tính");
        NV.add(NV_gioitinh);

        jMenuBar1.add(NV);

        Sach.setText("Sách");

        Sach_tacgia.setText("Theo tác giả");
        Sach.add(Sach_tacgia);

        Sach_theloai.setText("Theo thể loại");
        Sach_theloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sach_theloaiActionPerformed(evt);
            }
        });
        Sach.add(Sach_theloai);

        Sach_NhaXB.setText("Theo nhà xuất bản");
        Sach.add(Sach_NhaXB);

        Sach_namXB.setText("Theo năm xuất bản");
        Sach.add(Sach_namXB);

        jMenuBar1.add(Sach);

        MT.setText("Mượn trả");

        MT_ngay.setText("Sách mượn theo thể loại");
        MT.add(MT_ngay);

        MT_sachtheongay.setText("Sách mượn theo ngày");
        MT.add(MT_sachtheongay);

        MT_tiencoctheongay.setText("Tiền cọc của độc giả theo ngày");
        MT.add(MT_tiencoctheongay);

        MT_sodocgiatheongay.setText("Số đôc giả mượn theo ngày");
        MT.add(MT_sodocgiatheongay);

        MT_tienphattheongay.setText("Số tiền phạt của độc giả theo ngày");
        MT.add(MT_tienphattheongay);

        MT_madocgia.setText("Theo mã độc giả");
        MT.add(MT_madocgia);

        jMenuBar1.add(MT);

        jMenu2.setText("Thoát");

        jMenuItem21.setText("Yes");
        jMenu2.add(jMenuItem21);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DG_namsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DG_namsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DG_namsinhActionPerformed

    private void Sach_theloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sach_theloaiActionPerformed
DefaultTableModel tbn = new DefaultTableModel();
        Vector col = new Vector();
        try {
            thongke = "[Thể loại]";
            col.add(thongke);
            col.add("Số lượng");
            tbn.setColumnIdentifiers(col);
            ConnectionDB a = new ConnectionDB();
            Connection cnn = a.getConnectDB();
            PreparedStatement ps = cnn.prepareStatement(sql1 + " [Thể loại] ");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                row = new Vector();
                row.add(rs.getString("Thể loại"));
                PreparedStatement p = cnn.prepareStatement("select count(*) from Bangsach where [Thể loại] = '" + rs.getString("Thể loại") + "'");
                ResultSet r = p.executeQuery();
                r.first();
                row.add(r.getString("count(*)"));
                tbn.addRow(row);
                bangThongKe.setModel(tbn);
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Sach_theloaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DG;
    private javax.swing.JMenuItem DG_gioitinh;
    private javax.swing.JMenuItem DG_namsinh;
    private javax.swing.JMenuItem DG_quequan;
    private javax.swing.JMenu MT;
    private javax.swing.JMenuItem MT_madocgia;
    private javax.swing.JMenuItem MT_ngay;
    private javax.swing.JMenuItem MT_sachtheongay;
    private javax.swing.JMenuItem MT_sodocgiatheongay;
    private javax.swing.JMenuItem MT_tiencoctheongay;
    private javax.swing.JMenuItem MT_tienphattheongay;
    private javax.swing.JMenu NV;
    private javax.swing.JMenuItem NV_gioitinh;
    private javax.swing.JMenuItem NV_namsinh;
    private javax.swing.JMenuItem NV_quequan;
    private javax.swing.JMenu Sach;
    private javax.swing.JMenuItem Sach_NhaXB;
    private javax.swing.JMenuItem Sach_namXB;
    private javax.swing.JMenuItem Sach_tacgia;
    private javax.swing.JMenuItem Sach_theloai;
    private javax.swing.JTable bangThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
